server:
 port : 8088
  
#  
#logging:
#  level:
#    org.springframework: debug
#    
    
spring:
  messages:
    basename: messages
    
    
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    
